[build]
  # Serve static HTML directly - no build process
  publish = "public"
  command = "echo 'Serving static HTML'"

# Domain redirects - Both domains serve the same content
[[redirects]]
  from = "https://handy2know.com/*"
  to = "https://www.handy2know.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://handy2know.co.uk/*"
  to = "https://www.handy2know.co.uk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://handy2know.com/*"
  to = "https://www.handy2know.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://handy2know.co.uk/*"
  to = "https://www.handy2know.co.uk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.handy2know.com/*"
  to = "https://www.handy2know.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.handy2know.co.uk/*"
  to = "https://www.handy2know.co.uk/:splat"
  status = 301
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Cache static files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
