[build]
  # Build command for React app
  command = "npm run build"
  
  # Directory to publish (React build output)
  publish = "dist"
  
  # Base directory for build
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # NPM version  
  NPM_VERSION = "9"
  
  # React environment
  REACT_APP_ENV = "production"

# Redirect rules for Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://formsubmit.co https://js.stripe.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://formsubmit.co https://api.stripe.com; frame-src https://js.stripe.com https://hooks.stripe.com;"

# Cache control for index.html (no cache for SPA)
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Environment-specific settings
[context.production]
  command = "npm run build"
  
[context.production.environment]
  REACT_APP_ENV = "production"
  NODE_ENV = "production"

[context.deploy-preview]
  command = "npm run build"
  
[context.deploy-preview.environment]
  REACT_APP_ENV = "preview"

[context.branch-deploy]
  command = "npm run build"

# Build processing optimizations
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Form handling for FormSubmit integration
[[plugins]]
  package = "@netlify/plugin-sitemap"

# Auto-deployment configuration
# When connected to GitHub repository: handy2knowteam-creator/HTK-Web-App
# Branch: master
# Domain: www.handy2know.com
# SSL: Auto-enabled
# Deploy previews: Enabled for pull requests
